Added metrics to android checker
jobe-appstester/appstester_server pull request #14
Opened 2022-12-22 09:03 UTC by CAPCHIK

* Добавлены метрики количества подключенных устройств. Используется словарь, так как счетчик +- не подходит, могут пропасть события подключения/отключения, что приводит даже к отрицательным значениям
* В докер обернуты вспомогательные сервисы

open telemetry может раздавать метрики сразу для Prometheus, но делает это как слушатель порта, а прокидывать из Прометея в облаке доступ к android checker-у внутри сети университета(например) - не самая хорошая идея. Потому взят Open Telemetry Collector, который может собирать и метрики, и логи, и трассировки, и он уже потом эти данные может отдавать и Прометею, и зипкину, и кому угодно ещё

Пример получаемой статистики в графане на примере одного телефона
![image](https://user-images.githubusercontent.com/12235437/209097824-4a394ee4-daa6-4fec-bb6e-969cb199d3d5.png)

2023-02-15 18:58 UTC, devgavrilov requested changes

2023-02-21 07:36 UTC, CAPCHIK commented on AppsTester.Checker.Android/Adb/AdbClientProvider.cs
> +            SetupAdbServer(Path.Combine(configuration.GetValue<string>("ANDROID_SDK_ROOT"), "platform-tools", RuntimeInformation.IsOSPlatform(OSPlatform.Windows) ? "adb.exe" : "adb"));
В 186e32ae7e3d203565a4c750dbda293488abb144 доработал, вынес это как отдельный параметр в конфигурации, так как `host` и путь к исполняемому файлу не слишком связаны, вдруг нужно даже на локально запущенный сервер обязательно ходить через прокси

2023-02-28 08:58 UTC, XiRouz commented
В appsettings.json "ExecutablePath" надо бы ещё добавить

2023-02-28 09:32 UTC, CAPCHIK commented
> В appsettings.json "ExecutablePath" надо бы ещё добавить

Так он у каждого пользователя может быть свой, какой может подойти всем?

2023-02-28 09:41 UTC, XiRouz commented
> 

Просто пустую строку добавить (ExecutablePath: "" ), чтоб потом не надо было из кода вспоминать, как и куда в конфиг ExecutablePath дописывается. В методе IsNullOrEmpty ведь также вернётся false, если руками туда ничего не записывать.

2023-02-28 09:43 UTC, CAPCHIK commented
> > Так он у каждого пользователя может быть свой, какой может подойти всем?
> 
> Просто пустую строку добавить (ExecutablePath: "" ), чтоб потом не надо было из кода вспоминать, как и куда в конфиг ExecutablePath дописывается. В методе IsNullOrEmpty ведь также вернётся false, если руками туда ничего не записывать.

Ну, я придерживаюсь принципа документации, и вписал описание этого параметра в README, ибо appsettings по идее менять разработчик не должен. Если принято записывать такие параметры "чтобы было" - не проблема дописать

2023-03-02 08:43 UTC, merged